version: '3.9'
services:
  bicycle-rent:
    container_name: bicycle-rent
    build: .
    image: bicycle-rent
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bicycle_rent?useUnicode=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME : admin
      SPRING_DATASOURCE_PASSWORD : admin
      SPRING_JPA_SHOW-SQL : true
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    container_name: mysql-bicycle-rent
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: bicycle_rent
    ports:
      - "3307:3306"